FROM python:3.12-slim

WORKDIR /app

# Install Python dependencies
COPY  requirements.txt .
RUN pip install -r requirements.txt

# Copy app code
COPY . .

EXPOSE 5000

ENV PYTHONUNBUFFERED=1

CMD [ "python", "main.py" ]