FROM jenkins/jenkins:lts

# Switch to root to install dependencies or adjust permissions
USER root

# Optional: install Docker CLI (if you want Jenkins to build Docker containers)
RUN apt update && apt-get install -y \
    docker.io \
    wget \
    curl \
    python3 \
    python3-venv \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Install system dependencies
RUN apt-get update && apt-get install -y \
    firefox-esr \
    wget \
    ca-certificates \
    openssl  \
    libgtk-3-0 \
    libdbus-glib-1-2 \
    libasound2 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libgbm1 \
    libxshmfence1 \
    libxtst6 \
    fonts-liberation \
    && rm -rf /var/lib/apt/lists/*

# Install GeckoDriver
RUN GECKODRIVER_VERSION=0.34.0 && \
    wget -q https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER_VERSION}/geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz && \
    tar -xzf geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz && \
    mv geckodriver /usr/local/bin/ && \
    chmod +x /usr/local/bin/geckodriver && \
    rm geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz

# Download Gmail SMTP certificate and import into Java truststore
RUN mkdir -p /tmp/certs && \
    openssl s_client -showcerts -connect smtp.gmail.com:465 </dev/null 2>/dev/null | \
    openssl x509 -outform PEM > /tmp/certs/smtp_gmail.pem && \
    keytool -import -trustcacerts -noprompt \
    -alias gmail-smtp \
    -file /tmp/certs/smtp_gmail.pem \
    -keystore $JAVA_HOME/lib/security/cacerts \
    -storepass changeit && \
    rm -rf /tmp/certs

# Set environment variables (optional)
# ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
ENV JENKINS_JAVA_OPTS="-Dmail.smtp.ssl.trust=smtp.gmail.com"
ENV JAVA_OPTS="-Dmail.smtp.ssl.trust=smtp.gmail.com"

# Expose Jenkins ports
EXPOSE 8080 50000

# Set default user back to jenkins
USER jenkins

